name = "currencyconverter-pages"
pages_build_output_dir = "."
compatibility_date = "2024-10-01"

# KV namespace for currency rate caching
[[kv_namespaces]]
binding = "CURRENCY_RATES"
id = "210997d0fd1c4f56b15d6639682ecb09"

# Environment variables
[vars]
SITE_ORIGIN = "https://currencyconverter.org"

