name = "currencyconverter-pages"
pages_build_output_dir = "."
compatibility_date = "2024-10-01"

# KV namespace for currency rate caching
# Replace with actual ID after creating: npx wrangler kv:namespace create CURRENCY_RATES
[[kv_namespaces]]
binding = "CURRENCY_RATES"
id = "REPLACE_WITH_KV_ID"

# Environment variables
[vars]
SITE_ORIGIN = "https://currencyconverter.org"

