name = "currencyconverter-pages"
pages_build_output_dir = "."
compatibility_date = "2024-10-01"

# KV namespace for currency rate caching
[[kv_namespaces]]
binding = "CURRENCY_RATES"
id = "a323de077aa54d53b572ac835bf77aa4"

# Environment variables
[vars]
SITE_ORIGIN = "https://currencyconverter.org"

